server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: false
player_limit: -1
permissions:
  default:
    - bungeecord.command.server
    - bungeecord.command.list
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
    - bungeecord.command.kick
    - bungeecord.command.send
    - bungeecord.command.find
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
  - disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
listeners:
  - query_port: 25577
    motd: "§b§lPoloCloud §8» §7Simple Cloudsystem§8 [§b1.8 §7- §b1.20.x§8]\n§fGitHub §8× §fgithub.com/HttpMarco/polocloud"
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: false
    priorities:
      - lobby
    bind_local_address: true
    host: 0.0.0.0:25577
    max_players: 1
    tab_size: 60
    force_default_server: false
ip_forward: true
remote_ping_timeout: 5000
reject_transfers: false
prevent_proxy_connections: false
groups:
  md_5:
    - admin
connection_throttle: 4000
stats: adb64d7f-fd30-4547-8be5-b5409655087a
connection_throttle_limit: 3
log_pings: true
